#!/usr/bin/env node

/**
 * Setup script for Next.js Portfolio Boilerplate
 * This script helps users configure their portfolio quickly
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});

function ask(question) {
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      resolve(answer);
    });
  });
}

async function setup() {
  console.log('🚀 Next.js Portfolio Boilerplate Setup');
  console.log('=====================================\n');

  console.log('This script will help you configure your portfolio.\n');

  // Site Information
  console.log('📝 Site Information:');
  const siteName = await ask('Site name (e.g., "John Doe - Developer"): ');
  const siteDescription = await ask('Site description: ');
  const baseUrl = await ask('Base URL (e.g., https://yourdomain.com): ');

  // Personal Information
  console.log('\n👤 Personal Information:');
  const firstName = await ask('First name: ');
  const lastName = await ask('Last name: ');
  const email = await ask('Email: ');
  const bio = await ask('Short bio: ');

  // Job Information
  console.log('\n💼 Job Information:');
  const jobTitle = await ask('Job title: ');
  const company = await ask('Company: ');
  const companyWebsite = await ask('Company website: ');

  // Social Links
  console.log('\n🔗 Social Links:');
  const github = await ask('GitHub URL: ');
  const linkedin = await ask('LinkedIn URL: ');
  const twitter = await ask('Twitter URL (optional): ');

  // Features
  console.log('\n⚙️  Feature Configuration:');
  const enableShop = (await ask('Enable shop? (y/n): ')).toLowerCase() === 'y';
  const enableBlog = (await ask('Enable blog? (y/n): ')).toLowerCase() === 'y';

  // Generate .env.local
  const envContent = `# Environment Variables for Next.js Portfolio Boilerplate
# Generated by setup script - customize as needed

# ============================================
# Site Configuration
# ============================================

NEXT_PUBLIC_SITE_NAME="${siteName}"
NEXT_PUBLIC_SITE_DESCRIPTION="${siteDescription}"
NEXT_PUBLIC_BASE_URL="${baseUrl}"
NEXT_PUBLIC_OG_IMAGE="/images/open-graph-image.png"

# ============================================
# User Information
# ============================================

NEXT_PUBLIC_USER_FIRST_NAME="${firstName}"
NEXT_PUBLIC_USER_LAST_NAME="${lastName}"
NEXT_PUBLIC_USER_DISPLAY_NAME="${firstName} ${lastName}"
NEXT_PUBLIC_USER_USERNAME="${firstName.toLowerCase()}${lastName.toLowerCase()}"
NEXT_PUBLIC_USER_GENDER="male"
NEXT_PUBLIC_USER_PRONOUNS="he/him"
NEXT_PUBLIC_USER_BIO="${bio}"

CONTACT_EMAIL="${email}"
NEXT_PUBLIC_USER_EMAIL="${email}"
NEXT_PUBLIC_USER_PHONE=""
NEXT_PUBLIC_USER_WEBSITE="${baseUrl}"

NEXT_PUBLIC_USER_JOB_TITLE="${jobTitle}"
NEXT_PUBLIC_USER_COMPANY="${company}"
NEXT_PUBLIC_USER_COMPANY_WEBSITE="${companyWebsite}"

NEXT_PUBLIC_USER_ABOUT="Hello! I'm ${firstName} ${lastName}, ${bio}"

NEXT_PUBLIC_USER_AVATAR="/images/avatar.jpg"
NEXT_PUBLIC_USER_OG_IMAGE="/images/open-graph-image.png"

# ============================================
# Social Links
# ============================================

NEXT_PUBLIC_SOCIAL_TWITTER="${twitter || `https://twitter.com/${firstName.toLowerCase()}`}"
NEXT_PUBLIC_SOCIAL_GITHUB="${github}"
NEXT_PUBLIC_SOCIAL_LINKEDIN="${linkedin}"

# ============================================
# SEO and Keywords
# ============================================

NEXT_PUBLIC_SEO_KEYWORDS="portfolio,blog,developer,${firstName.toLowerCase()},${lastName.toLowerCase()}"

# ============================================
# Feature Toggles
# ============================================

NEXT_PUBLIC_ENABLE_SHOP=${enableShop}
NEXT_PUBLIC_ENABLE_BLOG=${enableBlog}
NEXT_PUBLIC_ENABLE_PROJECTS=true
NEXT_PUBLIC_ENABLE_CONTACT=true

# ============================================
# Third-party Services
# ============================================

# Add your API keys below
# RESEND_API_KEY=your_resend_api_key
# NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_your_key
# STRIPE_SECRET_KEY=sk_test_your_key
# NEXT_PUBLIC_POSTHOG_KEY=your_posthog_key

`;

  // Write .env.local
  fs.writeFileSync('.env.local', envContent);

  // Update package.json with user info
  const packagePath = path.join(__dirname, '..', 'package.json');
  const packageJson = JSON.parse(fs.readFileSync(packagePath, 'utf8'));

  packageJson.name = `${firstName.toLowerCase()}-${lastName.toLowerCase()}-portfolio`;
  packageJson.description = siteDescription;
  packageJson.author = {
    name: `${firstName} ${lastName}`,
    email: email,
    url: baseUrl
  };
  packageJson.repository = {
    type: "git",
    url: `git+https://github.com/${firstName.toLowerCase()}${lastName.toLowerCase()}/portfolio.git`
  };

  fs.writeFileSync(packagePath, JSON.stringify(packageJson, null, 2));

  console.log('\n✅ Setup Complete!');
  console.log('\nWhat\'s been configured:');
  console.log('• Environment variables (.env.local)');
  console.log('• Package.json metadata');
  console.log('\nNext steps:');
  console.log('1. Review and customize .env.local');
  console.log('2. Add your API keys (Stripe, PostHog, etc.)');
  console.log('3. Replace placeholder images in public/images/');
  console.log('4. Update content in features/about/content/about.mdx');
  console.log('5. Run "npm run dev" to start development');
  console.log('\nHappy coding! 🎉\n');

  rl.close();
}

setup().catch(console.error);
